fix: deploy scripts (#581)
Signed-off-by: Norman <norman@samourai.coop>

diff --git a/.github/workflows/deploy-staging.yml b/.github/workflows/deploy-staging.yml
--- a/.github/workflows/deploy-staging.yml
+++ b/.github/workflows/deploy-staging.yml
@@ -30,7 +30,7 @@ jobs:
 
       - name: Get current date
         id: date
-        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
+        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%s')"
 
       - name: Enable maintenance mode
         uses: appleboy/ssh-action@v1
@@ -39,22 +39,43 @@ jobs:
           username: root
           key: ${{ secrets.STAGING_SSH_KEY }}
           script: |
-            set -e
+            set -xe
             cd zenao
-            yq -i 'del(.services.backend.command)' staging.docker-compose.yml
-            yq -i '.services.backend |= ({"command": "--maintenance"} + .)' staging.docker-compose.yml
+            git fetch
+            git checkout ${{ github.sha }}
+            yq -iy 'del(.services.backend.command)' staging.docker-compose.yml
+            yq -iy '.services.backend |= ({"command": "--maintenance"} + .)' staging.docker-compose.yml
             docker compose -f staging.docker-compose.yml up -d backend
 
       - name: Backup DB
-        uses: tursodatabase/create-database-action@v1
-        with:
-          organization_name: samourai-coop
-          api_token: ${{ secrets.TURSO_API_TOKEN }}
-          existing_database_name: zenao-staging
-          new_database_name: zenao-staging-${{ steps.date.outputs.date }}
+        shell: bash
+        run: |
+          RESPONSE=$(curl -s -f -X POST \
+            -H "Authorization: Bearer ${{ secrets.TURSO_API_TOKEN }}" \
+            -H "Content-Type: application/json" \
+            -d '{"name": "zenao-staging-backup-${{ steps.date.outputs.date }}", "group": "zenao", "seed": {"type": "database", "name": "zenao-staging"} }' \
+                "https://api.turso.tech/v1/organizations/samourai-coop/databases")
+
+          if [ $? -ne 0 ]; then
+            echo "API call failed"
+            exit 1
+          fi
 
       - name: Migrate DB
         run: TURSO_TOKEN=${{ secrets.STAGING_TURSO_TOKEN }} atlas migrate apply --dir "file://migrations" --env staging
+
+      - name: Create genesis txs
+        run: go run ./backend gentxs -output genesis_txs.jsonl --db "libsql://zenao-staging-samourai-coop.turso.io?authToken=${{ secrets.STAGING_TURSO_TOKEN }}" --admin-mnemonic '${{ secrets.STAGING_ADMIN_MNEMONIC }}' --chain-id zenao-dev
+
+      - name: Copy genesis txs
+        uses: appleboy/scp-action@v1
+        with:
+          host: 51.159.98.163
+          username: root
+          key: ${{ secrets.STAGING_SSH_KEY }}
+          source: genesis_txs.jsonl
+          target: /root/zenao
+          overwrite: true
 
       - name: Upgrade services
         uses: appleboy/ssh-action@v1
@@ -63,11 +84,8 @@ jobs:
           username: root
           key: ${{ secrets.STAGING_SSH_KEY }}
           script: |
-            set -e
+            set -xe
             cd zenao
-            git fetch
-            git checkout ${{ github.sha }}
-            go run ./backend gentxs --db "libsql://zenao-staging-samourai-coop.turso.io?authToken=${{ secrets.STAGING_TURSO_TOKEN }}" --admin-mnemonic '${{ secrets.STAGING_ADMIN_MNEMONIC }}' --chain-id zenao-dev
-            docker compose -f staging.docker-compose.yml up -d --build gno --wait
-            yq -i 'del(.services.backend.command)' staging.docker-compose.yml
+            docker compose -f staging.docker-compose.yml up -d --force-recreate --build gno --wait
+            yq -iy 'del(.services.backend.command)' staging.docker-compose.yml
             docker compose -f staging.docker-compose.yml up -d --build backend
